In [43]:
import pandas as pd 
import tensorflow as tf
import numpy as np 
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix

In [8]:
tf.__version__

'2.12.1'

In [5]:
df = pd.read_csv('Churn_Modelling.csv')
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [9]:
dataset = df.copy()

In [11]:
dataset = dataset.drop(['CustomerId', 'RowNumber', 'Surname'], axis=1)
dataset.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [12]:
le = LabelEncoder()
dataset['Gender'] = le.fit_transform(dataset['Gender'])
dataset.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [13]:
dataset.Geography.value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [14]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [15]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [19]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [36]:
X

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

In [25]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [33]:
X_test

array([[-1.01558815,  1.76021608, -0.57468161, ...,  0.64365658,
         0.96668786,  1.61203027],
       [ 0.98465111, -0.56811207, -0.57468161, ...,  0.64365658,
        -1.03446007,  0.49626891],
       [-1.01558815, -0.56811207,  1.74009395, ...,  0.64365658,
         0.96668786, -0.42502785],
       ...,
       [ 0.98465111, -0.56811207, -0.57468161, ...,  0.64365658,
        -1.03446007, -0.272747  ],
       [-1.01558815,  1.76021608, -0.57468161, ...,  0.64365658,
        -1.03446007, -0.93306558],
       [ 0.98465111, -0.56811207, -0.57468161, ..., -1.55362351,
        -1.03446007, -0.47380732]])

### Making the artifical neural network !!

In [28]:
## INITIALIZE THE ARTIFICIAL NEURAL NETWORK
ann = tf.keras.models.Sequential()

In [29]:
# ADD THE INPUT LAYER AND THE FIRST HIDDEN LAYER 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [30]:
## ADD THE SECOND HIDDEN LAYER 
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [31]:
## ADD THE OUTPUT LAYER 
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [34]:
## COMPILE THE TRAIN AND TEST DATA
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [35]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


2023-09-18 16:16:20.141130: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


235/235 [==============================] - 1s 649us/step - loss: 0.7938 - accuracy: 0.4703
Epoch 2/100
235/235 [==============================] - 0s 596us/step - loss: 0.6261 - accuracy: 0.7821
Epoch 3/100
235/235 [==============================] - 0s 596us/step - loss: 0.5848 - accuracy: 0.7964
Epoch 4/100
235/235 [==============================] - 0s 597us/step - loss: 0.5574 - accuracy: 0.7963
Epoch 5/100
235/235 [==============================] - 0s 588us/step - loss: 0.5340 - accuracy: 0.7972
Epoch 6/100
235/235 [==============================] - 0s 592us/step - loss: 0.5094 - accuracy: 0.8053
Epoch 7/100
235/235 [==============================] - 0s 580us/step - loss: 0.4878 - accuracy: 0.8139
Epoch 8/100
235/235 [==============================] - 0s 589us/step - loss: 0.4708 - accuracy: 0.8176
Epoch 9/100
235/235 [==============================] - 0s 586us/step - loss: 0.4551 - accuracy: 0.8207
Epoch 10/100
235/235 [==============================] - 0s 580us/step - loss: 0.4390 

In [41]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 20ms/step
[[ True]]


In [42]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > .5)
np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

79/79 [==============================] - 0s 471us/step


array([[0, 0],
       [0, 1],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [45]:
print(confusion_matrix(y_pred, y_test))
print(accuracy_score(y_test, y_pred) * 100)

[[1884  240]
 [ 107  269]]
86.11999999999999
